version: "2"
services:
  omservice:
    build: .
    volumes:
      - ./:/app
    ports: [
      "3000:3000"
    ]
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.6.4-jessie
    ports: [
      "27017:27017"
    ]
    volumes:
      - /data/db:/data/db
    environment:
      - MONGODB_USER=root
      - MONGODB_PASSWORD=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_DATABASE=omdatabase
